apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.db.host }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.db.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.db.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-efs-pvc
