apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-efs-pvc
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Size doesn’t matter for EFS as it's dynamically scaled
  storageClassName: "efs-sc"
